
LET         = ('let',       True)
RETURN      = ('return',    True)
FN          = ('fn',        True)
IF          = ('if',        True)
ELSE        = ('else',      True)
EQ          = ('==',        False)
NOT_EQ      = ('!=',        False)
PLUS        = ('+',         False)
MINUS       = ('-',         False)
ASTERISK    = ('*',         False)
SLASH       = ('/',         False)
BANG        = ('!',         False)
LPAREN      = ('(',         False)
RPAREN      = (')',         False)
LBRACE      = ('{',         False)
RBRACE      = ('}',         False)
LBRACKET    = ('[',         False)
RBRACKET    = (']',         False)

STRING      = ('STRING',    False)
NUMBER      = ('NUMBER',    False)
